jobs:
  release:
    name: Release on Sonatype OSS
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      env:
        GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
      name: Setup gradle.properties
      run: 'mkdir -p ~/.gradle/

        echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV

        echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties

        '
      shell: bash
    - continue-on-error: true
      name: Build
      run: mvn clean install -DskipTests -q
    - continue-on-error: true
      name: Set up Maven Central
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        java-version: 17
        server-id: ossrh
        server-password: OSSRH_PASSWORD
        server-username: OSSRH_USERNAME
    - continue-on-error: true
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      name: Publish to Maven Central
      run: mvn -pl '!tests' clean deploy -P bom,central,gradlePlugin
name: Maven Central
on:
  repository_dispatch:
    types: trigger-ga___maven-central.yml
